#! /bin/bash

_japanesebot_zip () {
    if ([[ $PLUGINS_REPO ]])
    then
        echo "https://github.com/${PLUGINS_REPO}/archive/master.zip"
    else
        echo "https://github.com/kxunal/Plugins/archive/master.zip"
    fi
}

_starter () {
    echo "ᴅᴏᴡɴʟᴏᴀᴅɪɴɢ ᴊᴀᴘᴀɴᴇꜱᴇʙᴏᴛ [v4.5.1]"
    japanesebotpath="Plugins.zip"

    wget -q $(_japanesebot_zip) -O "$japanesebotpath"
    JAPANESEBOTPATH=$(zipinfo -1 "$japanesebotpath" | grep -v "/.");
    unzip -qq "$japanesebotpath"
    rm -rf "$japanesebotpath"
    cd $JAPANESEBOTPATH
    python3 ../updater.py ../requirements.txt requirements.txt

    echo "ꜱᴛᴀʀᴛɪɴɢ ᴊᴀᴘᴀɴᴇꜱᴇʙᴏᴛ [v4.5.1]"
    chmod 777 start.sh
    ./start.sh
}

_starter
